version: "3.9"

services:
  db:
    image: postgres:16
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: auth_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://user:pass@db:5432/auth"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "
        npx prisma migrate deploy || true &&
        npx prisma db seed || true &&
        npm run start:dev
      "

volumes:
  db_data:
