# Imagen base
FROM node:20-alpine
WORKDIR /app

# Copia archivos de dependencias
COPY package*.json ./

# Instala TODAS las dependencias (producción + desarrollo)
RUN npm install && npm cache clean --force

# Copia el código fuente y archivos de configuración
COPY prisma ./prisma
COPY src ./src
COPY tsconfig*.json ./
COPY nest-cli.json ./

# Genera el cliente de Prisma
RUN npx prisma generate

# Expone el puerto
EXPOSE 3000

# Comando de inicio en modo desarrollo
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:dev"]